# Render.com deployment configuration for SecondBrain API
# This file can be used for Infrastructure as Code deployment
# 
# Prerequisites:
# 1. Create a PostgreSQL database in Render dashboard
# 2. Set required environment variables (see envVars section below)
# 3. Connect this repository to Render
#
# Required secrets to set in Render dashboard:
# - DATABASE_URL: PostgreSQL connection string from your Render database
# - SECRET_KEY: Strong secret key (32+ characters) for JWT signing
# - OPENAI_API_KEY: Optional, for enhanced embeddings (can leave empty)

services:
  - type: web
    name: secondbrain-api
    env: python
    runtime: python-3.11
    plan: starter  # Change to pro as needed
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn backend.main:app --host 0.0.0.0 --port $PORT --workers 1"
    preDeployCommand: "alembic upgrade head"
    healthCheckPath: "/health"
    envVars:
      # Environment configuration
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: ENABLE_HTTPS
        value: true
      - key: LOG_LEVEL
        value: INFO
      - key: ENABLE_JSON_LOGGING
        value: true
      
      # CORS configuration for GitHub Pages frontend
      - key: GITHUB_PAGES_URL
        value: https://octopus-ai-secondbrain.github.io
      - key: GITHUB_PAGES_HOST  
        value: octopus-ai-secondbrain.github.io
      
      # Security settings
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      
      # Note: These MUST be set in Render dashboard as secrets:
      # DATABASE_URL: Your PostgreSQL database URL (auto-generated by Render)
      # SECRET_KEY: Strong random string (32+ characters)
      # OPENAI_API_KEY: Optional OpenAI API key
      
      # Optional: Set RENDER_EXTERNAL_URL to your actual Render domain
      # This will be auto-detected from RENDER service, but can be overridden

# Alternative manual setup commands for Render dashboard:
# 
# Build Command: 
#   pip install -r requirements.txt
# 
# Pre-Deploy Command: 
#   alembic upgrade head
# 
# Start Command: 
#   uvicorn backend.main:app --host 0.0.0.0 --port $PORT --workers 1
#
# Health Check Path:
#   /health
#
# Environment Variables to set in dashboard:
#   ENVIRONMENT=production
#   DEBUG=false  
#   ENABLE_HTTPS=true
#   LOG_LEVEL=INFO
#   ENABLE_JSON_LOGGING=true
#   GITHUB_PAGES_URL=https://octopus-ai-secondbrain.github.io
#   GITHUB_PAGES_HOST=octopus-ai-secondbrain.github.io
#   DATABASE_URL=[your postgres url]
#   SECRET_KEY=[your secret key]
#   OPENAI_API_KEY=[optional]