# Render.com deployment configuration
# This file can be used for Infrastructure as Code deployment

services:
  - type: web
    name: secondbrain-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn backend.main:app --host 0.0.0.0 --port $PORT"
    preDeployCommand: "python scripts/predeploy.py"
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: false
      - key: ENABLE_HTTPS
        value: true
      - key: LOG_LEVEL
        value: INFO
      - key: ENABLE_JSON_LOGGING
        value: true
      # Note: DATABASE_URL, SECRET_KEY, OPENAI_API_KEY should be set in Render dashboard
      # as they contain sensitive values

# Alternative manual commands for Render dashboard:
# Build Command: pip install -r requirements.txt
# Pre-Deploy Command: python scripts/predeploy.py
# Start Command: uvicorn backend.main:app --host 0.0.0.0 --port $PORT