# DigitalOcean App Platform Configuration - Dockerfile based
name: secondbrain-api
region: nyc

databases:
  - name: secondbrain-db
    engine: PG
    version: "15"
    size: db-s-dev-database
    num_nodes: 1
    production: false

services:
  - name: api
    github:
      repo: Octopus-AI-SecondBrain/Octopus-AI-SecondBrain.github.io
      branch: main
      deploy_on_push: true

    dockerfile_path: infra/Dockerfile.backend
    source_dir: /

    http_port: 8000

    instance_count: 1
    instance_size_slug: basic-xxs

    health_check:
      http_path: /api/healthz
      initial_delay_seconds: 60
      period_seconds: 30
      timeout_seconds: 10
      success_threshold: 1
      failure_threshold: 3

    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        value: ${secondbrain-db.DATABASE_URL}

      - key: SECRET_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
        value: "teEP8kwNfh1OkOtTyPnXsllJzePRIZ_5Q4D3N6EyGbE"

      - key: ENVIRONMENT
        scope: RUN_TIME
        value: "production"

      - key: DEBUG
        scope: RUN_TIME
        value: "false"

      - key: ENABLE_HTTPS
        scope: RUN_TIME
        value: "true"

      - key: LOG_LEVEL
        scope: RUN_TIME
        value: "INFO"

      - key: HOST
        scope: RUN_TIME
        value: "0.0.0.0"

      - key: PORT
        scope: RUN_TIME
        value: "8000"

      - key: CORS_ORIGINS
        scope: RUN_TIME
        value: "https://octopus-ai-secondbrain.github.io"

      - key: OPENAI_API_KEY
        scope: RUN_AND_BUILD_TIME
        type: SECRET
        value: ""

jobs:
  - name: migrate
    kind: PRE_DEPLOY
    github:
      repo: Octopus-AI-SecondBrain/Octopus-AI-SecondBrain.github.io
      branch: main
    dockerfile_path: infra/Dockerfile.backend
    source_dir: /
    run_command: alembic upgrade head
    environment_slug: python
    instance_count: 1
    instance_size_slug: basic-xxs
