name: Deploy to GitHub Pages

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches: [ main ]
    paths:
      - "frontend/**"
      - "docs/**"

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
        
    - name: Install dependencies
      run: |
        cd frontend
        npm ci
        
    - name: Build frontend
      run: |
        cd frontend
        npm run build
      env:
        NODE_ENV: production
        # Update this URL when you deploy backend to Render.com
        VITE_API_URL: https://secondbrain-api.onrender.com/api
        
    - name: Prepare GitHub Pages content
      run: |
        # Keep landing page at root (docs/)
        # Landing page files: index.html, styles.css, script.js already in docs/
        
        # Copy built app to docs/app subdirectory
        mkdir -p docs/app
        cp -r frontend/dist/* docs/app/
        
        # Create .nojekyll to bypass Jekyll processing
        touch docs/.nojekyll
        
        # Create 404 page that redirects to landing
        echo '<meta http-equiv="refresh" content="0; url=/">' > docs/404.html
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
        enable_jekyll: false
        force_orphan: true
        commit_message: 'Deploy landing page + app to GitHub Pages'
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'